#!/bin/bash
if [ "$DOCKER_TAG" == "latest" ]; then
    docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
else
    docker build --build-arg TARFILE=${DOCKER_TAG}.tar.gz -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi
